In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
def get_spam_number(x):
    if x == 'spam':
        return 1
    return 0
    

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [9]:
df.shape

(5572, 3)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

5291      Xy trying smth now. U eat already? We havent...
277                Tell rob to mack his gf in the theater
976     Hey no I ad a crap nite was borin without ya 2...
364     Busy here. Trying to finish for new year. I am...
Name: Message, dtype: object

In [16]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:4]

5291    0
277     0
976     0
364     0
Name: spam, dtype: int64

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59073 stored elements and shape (4457, 7739)>

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
X_train_cv.shape

(4457, 7739)

In [23]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [24]:
v.get_feature_names_out().shape

(7739,)

In [25]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr

In [26]:
v.vocabulary_

{'xy': 7656,
 'trying': 7055,
 'smth': 6255,
 'now': 4829,
 'eat': 2544,
 'already': 941,
 'we': 7410,
 'havent': 3381,
 'tell': 6742,
 'rob': 5789,
 'to': 6928,
 'mack': 4300,
 'his': 3462,
 'gf': 3158,
 'in': 3663,
 'the': 6804,
 'theater': 6807,
 'hey': 3442,
 'no': 4785,
 'ad': 828,
 'crap': 2086,
 'nite': 4778,
 'was': 7383,
 'borin': 1461,
 'without': 7544,
 'ya': 7657,
 'boggy': 1438,
 'with': 7540,
 'me': 4407,
 'boring': 1462,
 'biatch': 1362,
 'thanx': 6798,
 'but': 1598,
 'wait': 7344,
 'til': 6890,
 'nxt': 4856,
 'time': 6893,
 'il': 3632,
 'ave': 1166,
 'busy': 1597,
 'here': 3432,
 'finish': 2889,
 'for': 2973,
 'new': 4750,
 'year': 7672,
 'am': 952,
 'looking': 4207,
 'forward': 2998,
 'finally': 2881,
 'meeting': 4428,
 'you': 7698,
 'cheers': 1789,
 'lou': 4228,
 'yeah': 7671,
 'goodnite': 3216,
 'shame': 6050,
 'neva': 4745,
 'came': 1649,
 'gailxx': 3095,
 'ok': 4902,
 'lor': 4214,
 'your': 7703,
 'opinion': 4949,
 'about': 780,
 'over': 5014,
 'jada': 3804,
 'kusru

In [27]:
v.get_feature_names_out()[6847]

'thm'

In [29]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
np.where(X_train_np[0]!= 0)

(array([ 941, 2544, 3381, 4829, 6255, 7055, 7410, 7656], dtype=int64),)

In [33]:
X_train_np[0][755]

0

In [34]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [35]:
X_test_cv = v.transform(X_test)

In [37]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       972
           1       0.97      0.92      0.94       143

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [39]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [41]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [42]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [44]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       972
           1       0.97      0.92      0.94       143

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

